services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'DB_HOST=postgres'
      - 'DB_PORT=5432'
      - 'DB_NAME=bookmanageapp'
      - 'DB_USER=bookmanage_dev'
      - 'DB_PASSWORD=secret'
    volumes:
      - .:/workspace
    working_dir: /workspace

  postgres:
    image: 'postgres:17-alpine'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=bookmanageapp'
      - 'POSTGRES_USER=bookmanage_dev'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookmanage_dev -d bookmanageapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: